In [1]:
import numpy as np
import pandas as pd

In [44]:
df=pd.read_csv(r"C:\Users\razan\Downloads\Assignments Data Analysis\8 - Data Cleaning Python Assignments\audible_uncleaned.csv")
df

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [3]:
df['del']=df['author'].str.split(pat=':').str[0]
df

,name,author,narrator,time,releasedate,language,stars,price,del
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,Writtenby
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,Writtenby
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,Writtenby
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,Writtenby
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,Writtenby
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,Writtenby
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,Writtenby
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,Writtenby
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,Writtenby
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,Writtenby

In [4]:
df['author_name']=df['author'].str.split(pat=':').str[1]
df

,name,author,narrator,time,releasedate,language,stars,price,del,author_name
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,Writtenby,GeronimoStilton
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,Writtenby,RickRiordan
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,Writtenby,JeffKinney
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,Writtenby,RickRiordan
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,Writtenby,RickRiordan
...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,Writtenby,ChrisStewart
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,Writtenby,StephenO'Shea
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,Writtenby,MarkTwain
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,Writtenby,LaurenceSterne
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,Writtenby,MarkKurlansky

In [5]:
df=df.drop(columns='del')
df

,name,author,narrator,time,releasedate,language,stars,price,author_name
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,GeronimoStilton
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,RickRiordan
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,JeffKinney
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,RickRiordan
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,RickRiordan
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,ChrisStewart
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,StephenO'Shea
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,MarkTwain
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,LaurenceSterne
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,MarkKurlansky

In [6]:
df['narrator_name']=df['narrator'].str.split(pat=':').str[1]
df['dl']=df['narrator'].str.split(pat=':').str[0]
df

,name,author,narrator,time,releasedate,language,stars,price,author_name,narrator_name,dl
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely,Narratedby
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond,Narratedby
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell,Narratedby
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani,Narratedby
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein,Narratedby
...,...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,ChrisStewart,ChrisStewart,Narratedby
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,StephenO'Shea,RobertFass,Narratedby
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,MarkTwain,FloGibson,Narratedby
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,LaurenceSterne,AntonLesser,Narratedby
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,MarkKurlansky,FleetCooper,Narratedby

In [7]:
df=df.drop(columns='dl')
df

,name,author,narrator,time,releasedate,language,stars,price,author_name,narrator_name
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein
...,...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00,ChrisStewart,ChrisStewart
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00,StephenO'Shea,RobertFass
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00,MarkTwain,FloGibson
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00,LaurenceSterne,AntonLesser
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00,MarkKurlansky,FleetCooper

In [8]:
df=df.drop(columns='language')
df

,name,author,narrator,time,releasedate,stars,price,author_name,narrator_name
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper

In [9]:
df=df.drop(columns=['author','narrator'])
df

,name,time,releasedate,stars,price,author_name,narrator_name
0,Geronimo Stilton #11 & #12,2 hrs and 20 mins,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely
1,The Burning Maze,13 hrs and 8 mins,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond
2,The Deep End,2 hrs and 3 mins,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell
3,Daughter of the Deep,11 hrs and 16 mins,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10 hrs,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein
...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7 hrs and 34 mins,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart
87485,The Alps,10 hrs and 7 mins,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass
87486,The Innocents Abroad,19 hrs and 4 mins,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson
87487,A Sentimental Journey,4 hrs and 8 mins,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser
87488,Havana,6 hrs and 1 min,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper

In [10]:
df['time']=df['time'].str.rstrip(' mins ') 
df

,name,time,releasedate,stars,price,author_name,narrator_name
0,Geronimo Stilton #11 & #12,2 hrs and 20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely
1,The Burning Maze,13 hrs and 8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond
2,The Deep End,2 hrs and 3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell
3,Daughter of the Deep,11 hrs and 16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10 hr,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein
...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7 hrs and 34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart
87485,The Alps,10 hrs and 7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass
87486,The Innocents Abroad,19 hrs and 4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson
87487,A Sentimental Journey,4 hrs and 8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser
87488,Havana,6 hrs and 1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper

In [11]:
df['time'] = df['time'].str.replace(' hrs and ',':')
df

,name,time,releasedate,stars,price,author_name,narrator_name
0,Geronimo Stilton #11 & #12,2:20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely
1,The Burning Maze,13:8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond
2,The Deep End,2:3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell
3,Daughter of the Deep,11:16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10 hr,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein
...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart
87485,The Alps,10:7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass
87486,The Innocents Abroad,19:4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson
87487,A Sentimental Journey,4:8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser
87488,Havana,6:1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper

In [12]:
df['time'] = df['time'].str.replace(' hr','')
df

,name,time,releasedate,stars,price,author_name,narrator_name
0,Geronimo Stilton #11 & #12,2:20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely
1,The Burning Maze,13:8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond
2,The Deep End,2:3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell
3,Daughter of the Deep,11:16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein
...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart
87485,The Alps,10:7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass
87486,The Innocents Abroad,19:4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson
87487,A Sentimental Journey,4:8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser
87488,Havana,6:1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper

In [13]:
df['star']=df['stars'].str.split ('stars').str[0] 
df['del']=df['stars'].str.split ('stars').str[1] 
df

,name,time,releasedate,stars,price,author_name,narrator_name,star,del
0,Geronimo Stilton #11 & #12,2:20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely,5 out of 5,34 ratings
1,The Burning Maze,13:8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond,4.5 out of 5,41 ratings
2,The Deep End,2:3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell,4.5 out of 5,38 ratings
3,Daughter of the Deep,11:16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani,4.5 out of 5,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein,4.5 out of 5,181 ratings
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [14]:
df['star'] = df['star'].str.replace(' out of 5', '')
df

,name,time,releasedate,stars,price,author_name,narrator_name,star,del
0,Geronimo Stilton #11 & #12,2:20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely,5,34 ratings
1,The Burning Maze,13:8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond,4.5,41 ratings
2,The Deep End,2:3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell,4.5,38 ratings
3,Daughter of the Deep,11:16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani,4.5,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein,4.5,181 ratings
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [15]:
df=df.rename(columns={'del':'no. ratings'})
df

,name,time,releasedate,stars,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton #11 & #12,2:20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely,5,34 ratings
1,The Burning Maze,13:8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond,4.5,41 ratings
2,The Deep End,2:3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell,4.5,38 ratings
3,Daughter of the Deep,11:16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani,4.5,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein,4.5,181 ratings
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [16]:
df['no. ratings'] = df['no. ratings'].str.replace(' ratings', '')
df

,name,time,releasedate,stars,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton #11 & #12,2:20,04-08-08,5 out of 5 stars34 ratings,468.00,GeronimoStilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,4.5 out of 5 stars41 ratings,820.00,RickRiordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,4.5 out of 5 stars38 ratings,410.00,JeffKinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,4.5 out of 5 stars12 ratings,615.00,RickRiordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,4.5 out of 5 stars181 ratings,820.00,RickRiordan,JesseBernstein,4.5,181
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,Not rated yet,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,Not rated yet,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,Not rated yet,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,Not rated yet,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,Not rated yet,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [17]:
df=df.drop(columns='stars')
df

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton #11 & #12,2:20,04-08-08,468.00,GeronimoStilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,820.00,RickRiordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,410.00,JeffKinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,615.00,RickRiordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,RickRiordan,JesseBernstein,4.5,181
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [18]:
df['name'] = df['name'].str.replace('#', '')
df

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,GeronimoStilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,820.00,RickRiordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,410.00,JeffKinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,615.00,RickRiordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,RickRiordan,JesseBernstein,4.5,181
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [19]:
pd.set_option('display.max.rows',50)
df[df['name'].str.contains(r'[^a-zA-Z0-9 ]')].head(50)

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,GeronimoStilton,BillLobely,5,34
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,RickRiordan,JesseBernstein,4.5,181
5,The Hunger Games: Special Edition,10:35,30-10-18,656.00,SuzanneCollins,TatianaMaslany,5,72
9,The Tyrant’s Tomb,13:22,24-09-19,820.00,RickRiordan,RobbieDaymond,5,58
10,"The Titan's Curse: Percy Jackson, Book 3",8:48,14-01-10,820.00,RickRiordan,JesseBernstein,4.5,130
11,Magic Tree House Collection: Books 9-16,5:23,24-08-11,"1,206.00",MaryPopeOsborne,MaryPopeOsborne,5,6
12,Magic Tree House Collection: Books 1-8,6:1,27-09-11,"1,206.00",MaryPopeOsborne,MaryPopeOsborne,5,7
21,"Eldest: The Inheritance Cycle, Book 2",23:29,14-04-09,957.00,ChristopherPaolini,GerrardDoyle,4.5,47
23,Geronimo Stilton 22 & 24,2:37,01-02-11,469.00,GeronimoStilton,BillLobley,4.5,25
25,Winnie-the-Pooh,2:46,28-12-03,468.00,A.A.Milne,PeterDennis,5,15
26,Magic Tree House Collection: Books 25-32,7:9,01-09-20,"1,256.00",MaryPopeOsborne,MaryPopeOsborne,5,3
29,Mystery of the Griefer's Mark,1 and 53,25-11-14,233.00,WinterMorgan,LukeDaniels,5,9
34,"14 Short Stories Bundle for Kids: Adventure, S...",3:13,22-01-19,501.00,NayomiPhillips,"MonicaRachelle,JimD.Johnston,KatieOtten",Not rated yet,NaN
43,Rowley Jefferson's Awesome Friendly Adventure,1 and 31,04-08-20,410.00,JeffKinney,ChristopherGebauer,4,16
46,"The Lightning Thief: Percy Jackson, Book 1",3:51,13-01-10,615.00,RickRiordan,WalterLewis,4,4
53,The Gruffalo's Child,22,19-08-10,323.00,"JuliaDonaldson,AxelScheffler",ImeldaStaunton,4.5,4
58,Captain Underpants and the Revolting Revenge o...,2:10,02-11-21,445.00,DavPilkey,"LenForgione,AshtonSundholm,JadenRogers",5,1 rating
62,Unicorn Academy: Aisha and Silver,1 and 34,10-03-22,266.00,JulieSykes,KristinAtherton,Not rated yet,NaN
66,"The 39 Clues, Book 6",5:10,06-11-09,468.00,JudeWatson,DavidPittu,5,4
69,Unicorn Academy: Zara and Moonbeam,1 and 35,10-03-22,266.00,JulieSykes,KristinAtherton,Not rated yet,NaN
77,7 histoires d'aventures !,43,11-02-22,679.00,"BertrandFichou,NoraThullin,CatherinedeLasa,","GuyChappelier,FrédéricSanchez,MarieZidi,",Not rated yet,NaN
78,Le Loup qui devenait chef de la forêt,9,01-04-22,112.00,OrianneLallemand,WillProduction,Not rated yet,NaN
79,Curse of the Robo-Dragon,2:6,01-04-22,531.00,AdamBlade,TheoSolomon,Not rated yet,NaN
82,Captain Underpants and the Sensational Saga of...,1 and 37,05-04-22,586.00,DavPilkey,"LenForgione,WinstonBromhead,I'keMitchell",Not rated yet,NaN
85,Rowley Jefferson's Awesome Friendly Spooky Sto...,1 and 29,16-03-21,410.00,JeffKinney,ChristopherGebauer,3.5,7
91,"Fortunately, the Milk...",58,22-11-21,683.00,NeilGaiman,NeilGaiman,Not rated yet,NaN
95,An Explorer's Guide to the Nether,1 and 50,30-03-16,233.00,WinterMorgan,SummerMcCusker,5,4
98,The Squad of Lucky Landing: An Unofficial Fort...,2:11,30-10-18,585.00,DevinHunter,RamonDeOcampo,5,2
103,"The 39 Clues, Book 4",4:37,23-06-09,468.00,JudeWatson,DavidPittu,5,6
104,"The 39 Clues, Book 3",3:51,03-03-09,468.00,PeterLerangis,DavidPittu,5,9
109,Danger at Dead Man's Pass,6:48,16-09-21,323.00,"M.G.Leonard,SamSedgman,ElisaPaganelli-illustrator",JotDavies,Not rated yet,NaN
117,Barbie - Aventura espacial,12,02-02-22,76.00,"Mattel,MartaCisaMuñoz-traductor",MiriamMonlleo,Not rated yet,NaN
120,The Great Greenfield Bake-Off,1 and 41,01-09-21,234.00,GertrudeChandlerWarner,AimeeLilly,Not rated yet,NaN
123,The Magician's Nephew,3:55,29-08-05,303.00,C.S.Lewis,KennethBranagh,5,7
124,Leonora Bolt: Secret Inventor,2:55,20-01-22,410.00,LucyBrandt,NicoleDavis,Not rated yet,NaN
129,Captain Marvel - Ultron blir viral,11,11-01-22,32.00,"Marvel,CamillaDunér",MalinLybeck,Not rated yet,NaN
134,Barbie - La puerta secreta,11,29-11-21,38.00,"Mattel,NicolásOluchaSánchez",BeatrizOlcina,Not rated yet,NaN
135,A scuola con Pongo e Tim: Henry Every,11,09-02-22,75.00,GiuliaSegreti,"GiuliaSegreti,MarcoCognigni",Not rated yet,NaN
136,Black Panther: Spellbound,5:38,01-02-22,469.00,RonaldL.Smith,DionGraham,Not rated yet,NaN
137,"The 39 Clues: Unstoppable, Book 3",4:49,01-05-14,410.00,NatalieStandiford,DavidPittu,4.5,2
138,Hello Kitty - El Club de la Amistad,42,10-11-21,76.00,"Sanrio,NeusCasanovaVico",EvaAndrés,Not rated yet,NaN
141,Minecraft: The Dragon,6:51,06-07-21,"1,005.00",NickyDrayden,NicoleLewis,5,1 rating
144,El Cerdito de Navidad [The Christmas Pig],7:18,12-10-21,799.00,J.K.Rowling,CristinaTenorio,Not rated yet,NaN
146,The Imagination Box: Beyond Infinity,5:1,28-09-21,569.00,MartynFord,JoshuaMcGuire,Not rated yet,NaN
150,Little Badman and the Time-travelling Teacher ...,5:35,21-08-20,615.00,"HumzaArshad,HenryWhite",HumzaArshad,Not rated yet,NaN
152,Barbie - Superprincesa,26,15-10-21,38.00,"Mattel,NicolásOluchaSánchez",BeatrizOlcina,Not rated yet,NaN
153,Barbie - El campamento de princesas,33,07-03-22,38.00,Mattel,VanessaPérezJurado,Not rated yet,NaN
154,Barbie - Dreamtopia,21,07-03-22,38.00,Mattel,VanessaPérezJurado,Not rated yet,NaN
155,Barbie - Superprincesa,29,07-03-22,38.00,Mattel,VanessaPérezJurado,Not rated yet,NaN
156,Among Us Book - Red Diary,1 and 19,16-06-21,204.00,ZeekidMedia,TommyJay,Not rated yet,NaN

In [20]:
df['time'] = df['time'].str.replace(' and ', ':')
df

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,GeronimoStilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,820.00,RickRiordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,410.00,JeffKinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,615.00,RickRiordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,RickRiordan,JesseBernstein,4.5,181
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,ChrisStewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,820.00,StephenO'Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,938.00,MarkTwain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,680.00,LaurenceSterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,569.00,MarkKurlansky,FleetCooper,Not rated yet,NaN

In [21]:
df.head(50)

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,GeronimoStilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,820.00,RickRiordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,410.00,JeffKinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,615.00,RickRiordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,RickRiordan,JesseBernstein,4.5,181
5,The Hunger Games: Special Edition,10:35,30-10-18,656.00,SuzanneCollins,TatianaMaslany,5,72
6,Quest for the Diamond Sword,2:23,25-11-14,233.00,WinterMorgan,LukeDaniels,5,11
7,The Dark Prophecy,12:32,02-05-17,820.00,RickRiordan,RobbieDaymond,5,50
8,Merlin Mission Collection,10:56,02-05-17,"1,256.00",MaryPopeOsborne,MaryPopeOsborne,5,5
9,The Tyrant’s Tomb,13:22,24-09-19,820.00,RickRiordan,RobbieDaymond,5,58
10,"The Titan's Curse: Percy Jackson, Book 3",8:48,14-01-10,820.00,RickRiordan,JesseBernstein,4.5,130
11,Magic Tree House Collection: Books 9-16,5:23,24-08-11,"1,206.00",MaryPopeOsborne,MaryPopeOsborne,5,6
12,Magic Tree House Collection: Books 1-8,6:1,27-09-11,"1,206.00",MaryPopeOsborne,MaryPopeOsborne,5,7
13,Magnus Chase and the Ship of the Dead,12:58,03-10-17,820.00,RickRiordan,MichaelCrouch,5,41
14,Northern Lights,11:55,24-06-21,"1,093.00",PhilipPullman,"PhilipPullman,fullcast,RuthWilson",4,2
15,Geronimo Stilton 13 and 14,2:25,08-02-08,467.00,GeronimoStilton,BillLobley,4.5,33
16,Magic Tree House Collection,5:4,26-12-04,"1,206.00",MaryPopeOsborne,MaryPopeOsborne,5,7
17,Exile,14:41,06-11-18,836.00,ShannonMessenger,CaitlinKelly,5,20
18,Merlin Mission Collection,10:18,02-05-17,"1,256.00",MaryPopeOsborne,MaryPopeOsborne,5,11
19,Neverseen,16:42,06-11-18,"1,003.00",ShannonMessenger,CaitlinKelly,5,13
20,The Tower of Nero,12:12,06-10-20,615.00,RickRiordan,RobbieDaymond,5,79
21,"Eldest: The Inheritance Cycle, Book 2",23:29,14-04-09,957.00,ChristopherPaolini,GerrardDoyle,4.5,47
22,Artemis Fowl,6:46,11-04-13,683.00,EoinColfer,GerryO'Brien,5,27
23,Geronimo Stilton 22 & 24,2:37,01-02-11,469.00,GeronimoStilton,BillLobley,4.5,25
24,Percy Jackson and the Battle of the Labyrinth,10:32,21-01-10,820.00,RickRiordan,JesseBernstein,5,101
25,Winnie-the-Pooh,2:46,28-12-03,468.00,A.A.Milne,PeterDennis,5,15
26,Magic Tree House Collection: Books 25-32,7:9,01-09-20,"1,256.00",MaryPopeOsborne,MaryPopeOsborne,5,3
27,Geronimo Stilton 20 and 21,2:32,01-10-10,469.00,GeronimoStilton,BillLobley,5,18
28,The Red Pyramid,13:44,24-01-13,820.00,RickRiordan,"JaneCollingwood,JosephMay",4.5,37
29,Mystery of the Griefer's Mark,1:53,25-11-14,233.00,WinterMorgan,LukeDaniels,5,9
30,Geronimo Stilton 17,2:28,13-07-09,468.00,GeronimoStilton,BillLobley,5,8
31,The House at Pooh Corner,3:12,05-04-05,374.00,A.A.Milne,PeterDennis,5,5
32,Mission Unstoppable,6:8,01-08-13,702.00,DanGutman,MichaelGoldstrom,5,8
33,Darkness of Dragons,10:26,01-08-17,656.00,TuiT.Sutherland,ShannonMcManus,5,8
34,"14 Short Stories Bundle for Kids: Adventure, S...",3:13,22-01-19,501.00,NayomiPhillips,"MonicaRachelle,JimD.Johnston,KatieOtten",Not rated yet,NaN
35,The Adventures of Rusty,5:41,01-11-18,284.00,RuskinBond,NehaGargava,4.5,10
36,Geronimo Stilton 15 and 16,2:43,08-02-08,467.00,GeronimoStilton,BillLobley,4,28
37,The Lost Heir,7:23,04-02-16,575.00,TuiT.Sutherland,ShannonMcManus,5,9
38,Everblaze,14:39,06-11-18,836.00,ShannonMessenger,CaitlinKelly,5,18
39,Treasure Hunters in Trouble,1:58,31-03-15,668.00,WinterMorgan,LukeDaniels,5,7
40,Lodestar,16:31,06-11-18,"1,003.00",ShannonMessenger,CaitlinKelly,5,19
41,Curse of the Arctic Star,3:35,28-12-14,305.00,CarolynKeene,JorjeanaMarie,4.5,25
42,The Ghost of Grey Fox Inn,3:19,20-03-17,305.00,CarolynKeene,JorjeanaMarie,5,11
43,Rowley Jefferson's Awesome Friendly Adventure,1:31,04-08-20,410.00,JeffKinney,ChristopherGebauer,4,16
44,Flashback,23:9,11-12-18,"1,170.00",ShannonMessenger,CaitlinKelly,5,12
45,Secret of the Red Arrow,3:33,04-11-15,305.00,FranklinW.Dixon,TimGregory,4.5,16
46,"The Lightning Thief: Percy Jackson, Book 1",3:51,13-01-10,615.00,RickRiordan,WalterLewis,4,4
47,Clash of the Creepers,2:1,07-07-15,233.00,WinterMorgan,LukeDaniels,5,10
48,The Skeletons Strike Back,2:1,07-07-15,233.00,WinterMorgan,LukeDaniels,5,7
49,Dragonslayer,12:44,03-03-20,656.00,TuiT.Sutherland,ShannonMcManus,5,17

In [22]:
df['author_name']=df['author_name'].str.replace(r'([A-Z])',r' \1',regex=True)
df

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,JesseBernstein,4.5,181
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,Chris Stewart,ChrisStewart,Not rated yet,NaN
87485,The Alps,10:7,21-02-17,820.00,Stephen O' Shea,RobertFass,Not rated yet,NaN
87486,The Innocents Abroad,19:4,30-12-16,938.00,Mark Twain,FloGibson,Not rated yet,NaN
87487,A Sentimental Journey,4:8,23-02-11,680.00,Laurence Sterne,AntonLesser,Not rated yet,NaN
87488,Havana,6:1,07-03-17,569.00,Mark Kurlansky,FleetCooper,Not rated yet,NaN

In [23]:
df.head(50)

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,BillLobely,5,34
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,RobbieDaymond,4.5,41
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,DanRussell,4.5,38
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,SoneelaNankani,4.5,12
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,JesseBernstein,4.5,181
5,The Hunger Games: Special Edition,10:35,30-10-18,656.00,Suzanne Collins,TatianaMaslany,5,72
6,Quest for the Diamond Sword,2:23,25-11-14,233.00,Winter Morgan,LukeDaniels,5,11
7,The Dark Prophecy,12:32,02-05-17,820.00,Rick Riordan,RobbieDaymond,5,50
8,Merlin Mission Collection,10:56,02-05-17,"1,256.00",Mary Pope Osborne,MaryPopeOsborne,5,5
9,The Tyrant’s Tomb,13:22,24-09-19,820.00,Rick Riordan,RobbieDaymond,5,58
10,"The Titan's Curse: Percy Jackson, Book 3",8:48,14-01-10,820.00,Rick Riordan,JesseBernstein,4.5,130
11,Magic Tree House Collection: Books 9-16,5:23,24-08-11,"1,206.00",Mary Pope Osborne,MaryPopeOsborne,5,6
12,Magic Tree House Collection: Books 1-8,6:1,27-09-11,"1,206.00",Mary Pope Osborne,MaryPopeOsborne,5,7
13,Magnus Chase and the Ship of the Dead,12:58,03-10-17,820.00,Rick Riordan,MichaelCrouch,5,41
14,Northern Lights,11:55,24-06-21,"1,093.00",Philip Pullman,"PhilipPullman,fullcast,RuthWilson",4,2
15,Geronimo Stilton 13 and 14,2:25,08-02-08,467.00,Geronimo Stilton,BillLobley,4.5,33
16,Magic Tree House Collection,5:4,26-12-04,"1,206.00",Mary Pope Osborne,MaryPopeOsborne,5,7
17,Exile,14:41,06-11-18,836.00,Shannon Messenger,CaitlinKelly,5,20
18,Merlin Mission Collection,10:18,02-05-17,"1,256.00",Mary Pope Osborne,MaryPopeOsborne,5,11
19,Neverseen,16:42,06-11-18,"1,003.00",Shannon Messenger,CaitlinKelly,5,13
20,The Tower of Nero,12:12,06-10-20,615.00,Rick Riordan,RobbieDaymond,5,79
21,"Eldest: The Inheritance Cycle, Book 2",23:29,14-04-09,957.00,Christopher Paolini,GerrardDoyle,4.5,47
22,Artemis Fowl,6:46,11-04-13,683.00,Eoin Colfer,GerryO'Brien,5,27
23,Geronimo Stilton 22 & 24,2:37,01-02-11,469.00,Geronimo Stilton,BillLobley,4.5,25
24,Percy Jackson and the Battle of the Labyrinth,10:32,21-01-10,820.00,Rick Riordan,JesseBernstein,5,101
25,Winnie-the-Pooh,2:46,28-12-03,468.00,A. A. Milne,PeterDennis,5,15
26,Magic Tree House Collection: Books 25-32,7:9,01-09-20,"1,256.00",Mary Pope Osborne,MaryPopeOsborne,5,3
27,Geronimo Stilton 20 and 21,2:32,01-10-10,469.00,Geronimo Stilton,BillLobley,5,18
28,The Red Pyramid,13:44,24-01-13,820.00,Rick Riordan,"JaneCollingwood,JosephMay",4.5,37
29,Mystery of the Griefer's Mark,1:53,25-11-14,233.00,Winter Morgan,LukeDaniels,5,9
30,Geronimo Stilton 17,2:28,13-07-09,468.00,Geronimo Stilton,BillLobley,5,8
31,The House at Pooh Corner,3:12,05-04-05,374.00,A. A. Milne,PeterDennis,5,5
32,Mission Unstoppable,6:8,01-08-13,702.00,Dan Gutman,MichaelGoldstrom,5,8
33,Darkness of Dragons,10:26,01-08-17,656.00,Tui T. Sutherland,ShannonMcManus,5,8
34,"14 Short Stories Bundle for Kids: Adventure, S...",3:13,22-01-19,501.00,Nayomi Phillips,"MonicaRachelle,JimD.Johnston,KatieOtten",Not rated yet,NaN
35,The Adventures of Rusty,5:41,01-11-18,284.00,Ruskin Bond,NehaGargava,4.5,10
36,Geronimo Stilton 15 and 16,2:43,08-02-08,467.00,Geronimo Stilton,BillLobley,4,28
37,The Lost Heir,7:23,04-02-16,575.00,Tui T. Sutherland,ShannonMcManus,5,9
38,Everblaze,14:39,06-11-18,836.00,Shannon Messenger,CaitlinKelly,5,18
39,Treasure Hunters in Trouble,1:58,31-03-15,668.00,Winter Morgan,LukeDaniels,5,7
40,Lodestar,16:31,06-11-18,"1,003.00",Shannon Messenger,CaitlinKelly,5,19
41,Curse of the Arctic Star,3:35,28-12-14,305.00,Carolyn Keene,JorjeanaMarie,4.5,25
42,The Ghost of Grey Fox Inn,3:19,20-03-17,305.00,Carolyn Keene,JorjeanaMarie,5,11
43,Rowley Jefferson's Awesome Friendly Adventure,1:31,04-08-20,410.00,Jeff Kinney,ChristopherGebauer,4,16
44,Flashback,23:9,11-12-18,"1,170.00",Shannon Messenger,CaitlinKelly,5,12
45,Secret of the Red Arrow,3:33,04-11-15,305.00,Franklin W. Dixon,TimGregory,4.5,16
46,"The Lightning Thief: Percy Jackson, Book 1",3:51,13-01-10,615.00,Rick Riordan,WalterLewis,4,4
47,Clash of the Creepers,2:1,07-07-15,233.00,Winter Morgan,LukeDaniels,5,10
48,The Skeletons Strike Back,2:1,07-07-15,233.00,Winter Morgan,LukeDaniels,5,7
49,Dragonslayer,12:44,03-03-20,656.00,Tui T. Sutherland,ShannonMcManus,5,17

In [24]:
df['narrator_name1']=df['narrator_name'].str.split(pat=',').str[0]
df

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings,narrator_name1
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,BillLobely,5,34,BillLobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,RobbieDaymond,4.5,41,RobbieDaymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,DanRussell,4.5,38,DanRussell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,SoneelaNankani,4.5,12,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,JesseBernstein,4.5,181,JesseBernstein
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,Chris Stewart,ChrisStewart,Not rated yet,NaN,ChrisStewart
87485,The Alps,10:7,21-02-17,820.00,Stephen O' Shea,RobertFass,Not rated yet,NaN,RobertFass
87486,The Innocents Abroad,19:4,30-12-16,938.00,Mark Twain,FloGibson,Not rated yet,NaN,FloGibson
87487,A Sentimental Journey,4:8,23-02-11,680.00,Laurence Sterne,AntonLesser,Not rated yet,NaN,AntonLesser
87488,Havana,6:1,07-03-17,569.00,Mark Kurlansky,FleetCooper,Not rated yet,NaN,FleetCooper

In [25]:
df['narrator_name2']=df['narrator_name'].str.split(pat=',').str[1]
df['narrator_name3']=df['narrator_name'].str.split(pat=',').str[2]
df.head(50)

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings,narrator_name1,narrator_name2,narrator_name3
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,BillLobely,5,34,BillLobely,NaN,NaN
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,RobbieDaymond,4.5,41,RobbieDaymond,NaN,NaN
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,DanRussell,4.5,38,DanRussell,NaN,NaN
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,SoneelaNankani,4.5,12,SoneelaNankani,NaN,NaN
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,JesseBernstein,4.5,181,JesseBernstein,NaN,NaN
5,The Hunger Games: Special Edition,10:35,30-10-18,656.00,Suzanne Collins,TatianaMaslany,5,72,TatianaMaslany,NaN,NaN
6,Quest for the Diamond Sword,2:23,25-11-14,233.00,Winter Morgan,LukeDaniels,5,11,LukeDaniels,NaN,NaN
7,The Dark Prophecy,12:32,02-05-17,820.00,Rick Riordan,RobbieDaymond,5,50,RobbieDaymond,NaN,NaN
8,Merlin Mission Collection,10:56,02-05-17,"1,256.00",Mary Pope Osborne,MaryPopeOsborne,5,5,MaryPopeOsborne,NaN,NaN
9,The Tyrant’s Tomb,13:22,24-09-19,820.00,Rick Riordan,RobbieDaymond,5,58,RobbieDaymond,NaN,NaN
10,"The Titan's Curse: Percy Jackson, Book 3",8:48,14-01-10,820.00,Rick Riordan,JesseBernstein,4.5,130,JesseBernstein,NaN,NaN
11,Magic Tree House Collection: Books 9-16,5:23,24-08-11,"1,206.00",Mary Pope Osborne,MaryPopeOsborne,5,6,MaryPopeOsborne,NaN,NaN
12,Magic Tree House Collection: Books 1-8,6:1,27-09-11,"1,206.00",Mary Pope Osborne,MaryPopeOsborne,5,7,MaryPopeOsborne,NaN,NaN
13,Magnus Chase and the Ship of the Dead,12:58,03-10-17,820.00,Rick Riordan,MichaelCrouch,5,41,MichaelCrouch,NaN,NaN
14,Northern Lights,11:55,24-06-21,"1,093.00",Philip Pullman,"PhilipPullman,fullcast,RuthWilson",4,2,PhilipPullman,fullcast,RuthWilson
15,Geronimo Stilton 13 and 14,2:25,08-02-08,467.00,Geronimo Stilton,BillLobley,4.5,33,BillLobley,NaN,NaN
16,Magic Tree House Collection,5:4,26-12-04,"1,206.00",Mary Pope Osborne,MaryPopeOsborne,5,7,MaryPopeOsborne,NaN,NaN
17,Exile,14:41,06-11-18,836.00,Shannon Messenger,CaitlinKelly,5,20,CaitlinKelly,NaN,NaN
18,Merlin Mission Collection,10:18,02-05-17,"1,256.00",Mary Pope Osborne,MaryPopeOsborne,5,11,MaryPopeOsborne,NaN,NaN
19,Neverseen,16:42,06-11-18,"1,003.00",Shannon Messenger,CaitlinKelly,5,13,CaitlinKelly,NaN,NaN
20,The Tower of Nero,12:12,06-10-20,615.00,Rick Riordan,RobbieDaymond,5,79,RobbieDaymond,NaN,NaN
21,"Eldest: The Inheritance Cycle, Book 2",23:29,14-04-09,957.00,Christopher Paolini,GerrardDoyle,4.5,47,GerrardDoyle,NaN,NaN
22,Artemis Fowl,6:46,11-04-13,683.00,Eoin Colfer,GerryO'Brien,5,27,GerryO'Brien,NaN,NaN
23,Geronimo Stilton 22 & 24,2:37,01-02-11,469.00,Geronimo Stilton,BillLobley,4.5,25,BillLobley,NaN,NaN
24,Percy Jackson and the Battle of the Labyrinth,10:32,21-01-10,820.00,Rick Riordan,JesseBernstein,5,101,JesseBernstein,NaN,NaN
25,Winnie-the-Pooh,2:46,28-12-03,468.00,A. A. Milne,PeterDennis,5,15,PeterDennis,NaN,NaN
26,Magic Tree House Collection: Books 25-32,7:9,01-09-20,"1,256.00",Mary Pope Osborne,MaryPopeOsborne,5,3,MaryPopeOsborne,NaN,NaN
27,Geronimo Stilton 20 and 21,2:32,01-10-10,469.00,Geronimo Stilton,BillLobley,5,18,BillLobley,NaN,NaN
28,The Red Pyramid,13:44,24-01-13,820.00,Rick Riordan,"JaneCollingwood,JosephMay",4.5,37,JaneCollingwood,JosephMay,NaN
29,Mystery of the Griefer's Mark,1:53,25-11-14,233.00,Winter Morgan,LukeDaniels,5,9,LukeDaniels,NaN,NaN
30,Geronimo Stilton 17,2:28,13-07-09,468.00,Geronimo Stilton,BillLobley,5,8,BillLobley,NaN,NaN
31,The House at Pooh Corner,3:12,05-04-05,374.00,A. A. Milne,PeterDennis,5,5,PeterDennis,NaN,NaN
32,Mission Unstoppable,6:8,01-08-13,702.00,Dan Gutman,MichaelGoldstrom,5,8,MichaelGoldstrom,NaN,NaN
33,Darkness of Dragons,10:26,01-08-17,656.00,Tui T. Sutherland,ShannonMcManus,5,8,ShannonMcManus,NaN,NaN
34,"14 Short Stories Bundle for Kids: Adventure, S...",3:13,22-01-19,501.00,Nayomi Phillips,"MonicaRachelle,JimD.Johnston,KatieOtten",Not rated yet,NaN,MonicaRachelle,JimD.Johnston,KatieOtten
35,The Adventures of Rusty,5:41,01-11-18,284.00,Ruskin Bond,NehaGargava,4.5,10,NehaGargava,NaN,NaN
36,Geronimo Stilton 15 and 16,2:43,08-02-08,467.00,Geronimo Stilton,BillLobley,4,28,BillLobley,NaN,NaN
37,The Lost Heir,7:23,04-02-16,575.00,Tui T. Sutherland,ShannonMcManus,5,9,ShannonMcManus,NaN,NaN
38,Everblaze,14:39,06-11-18,836.00,Shannon Messenger,CaitlinKelly,5,18,CaitlinKelly,NaN,NaN
39,Treasure Hunters in Trouble,1:58,31-03-15,668.00,Winter Morgan,LukeDaniels,5,7,LukeDaniels,NaN,NaN
40,Lodestar,16:31,06-11-18,"1,003.00",Shannon Messenger,CaitlinKelly,5,19,CaitlinKelly,NaN,NaN
41,Curse of the Arctic Star,3:35,28-12-14,305.00,Carolyn Keene,JorjeanaMarie,4.5,25,JorjeanaMarie,NaN,NaN
42,The Ghost of Grey Fox Inn,3:19,20-03-17,305.00,Carolyn Keene,JorjeanaMarie,5,11,JorjeanaMarie,NaN,NaN
43,Rowley Jefferson's Awesome Friendly Adventure,1:31,04-08-20,410.00,Jeff Kinney,ChristopherGebauer,4,16,ChristopherGebauer,NaN,NaN
44,Flashback,23:9,11-12-18,"1,170.00",Shannon Messenger,CaitlinKelly,5,12,CaitlinKelly,NaN,NaN
45,Secret of the Red Arrow,3:33,04-11-15,305.00,Franklin W. Dixon,TimGregory,4.5,16,TimGregory,NaN,NaN
46,"The Lightning Thief: Percy Jackson, Book 1",3:51,13-01-10,615.00,Rick Riordan,WalterLewis,4,4,WalterLewis,NaN,NaN
47,Clash of the Creepers,2:1,07-07-15,233.00,Winter Morgan,LukeDaniels,5,10,LukeDaniels,NaN,NaN
48,The Skeletons Strike Back,2:1,07-07-15,233.00,Winter Morgan,LukeDaniels,5,7,LukeDaniels,NaN,NaN
49,Dragonslayer,12:44,03-03-20,656.00,Tui T. Sutherland,ShannonMcManus,5,17,ShannonMcManus,NaN,NaN

In [26]:
df['narrator_name2'].isnull().sum()

75754

In [27]:
df=df.drop(columns=['narrator_name2','narrator_name3'])
df

,name,time,releasedate,price,author_name,narrator_name,star,no. ratings,narrator_name1
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,BillLobely,5,34,BillLobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,RobbieDaymond,4.5,41,RobbieDaymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,DanRussell,4.5,38,DanRussell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,SoneelaNankani,4.5,12,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,JesseBernstein,4.5,181,JesseBernstein
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,Chris Stewart,ChrisStewart,Not rated yet,NaN,ChrisStewart
87485,The Alps,10:7,21-02-17,820.00,Stephen O' Shea,RobertFass,Not rated yet,NaN,RobertFass
87486,The Innocents Abroad,19:4,30-12-16,938.00,Mark Twain,FloGibson,Not rated yet,NaN,FloGibson
87487,A Sentimental Journey,4:8,23-02-11,680.00,Laurence Sterne,AntonLesser,Not rated yet,NaN,AntonLesser
87488,Havana,6:1,07-03-17,569.00,Mark Kurlansky,FleetCooper,Not rated yet,NaN,FleetCooper

In [28]:
df=df.drop(columns='narrator_name')
df

,name,time,releasedate,price,author_name,star,no. ratings,narrator_name1
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,5,34,BillLobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,4.5,41,RobbieDaymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,4.5,38,DanRussell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,4.5,12,SoneelaNankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,4.5,181,JesseBernstein
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,Chris Stewart,Not rated yet,NaN,ChrisStewart
87485,The Alps,10:7,21-02-17,820.00,Stephen O' Shea,Not rated yet,NaN,RobertFass
87486,The Innocents Abroad,19:4,30-12-16,938.00,Mark Twain,Not rated yet,NaN,FloGibson
87487,A Sentimental Journey,4:8,23-02-11,680.00,Laurence Sterne,Not rated yet,NaN,AntonLesser
87488,Havana,6:1,07-03-17,569.00,Mark Kurlansky,Not rated yet,NaN,FleetCooper

In [32]:
df['narrator_name1']=df['narrator_name1'].str.replace(r'([A-Z])',r' \1',regex=True)

df

,name,time,releasedate,price,author_name,star,no. ratings,narrator_name1
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,5,34,Bill Lobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,4.5,41,Robbie Daymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,4.5,38,Dan Russell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,4.5,12,Soneela Nankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,4.5,181,Jesse Bernstein
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,Chris Stewart,Not rated yet,NaN,Chris Stewart
87485,The Alps,10:7,21-02-17,820.00,Stephen O' Shea,Not rated yet,NaN,Robert Fass
87486,The Innocents Abroad,19:4,30-12-16,938.00,Mark Twain,Not rated yet,NaN,Flo Gibson
87487,A Sentimental Journey,4:8,23-02-11,680.00,Laurence Sterne,Not rated yet,NaN,Anton Lesser
87488,Havana,6:1,07-03-17,569.00,Mark Kurlansky,Not rated yet,NaN,Fleet Cooper

In [36]:
df.head(50)

,name,time,releasedate,price,author_name,star,no. ratings,narrator_name1
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,5,34,Bill Lobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,4.5,41,Robbie Daymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,4.5,38,Dan Russell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,4.5,12,Soneela Nankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,4.5,181,Jesse Bernstein
5,The Hunger Games: Special Edition,10:35,30-10-18,656.00,Suzanne Collins,5,72,Tatiana Maslany
6,Quest for the Diamond Sword,2:23,25-11-14,233.00,Winter Morgan,5,11,Luke Daniels
7,The Dark Prophecy,12:32,02-05-17,820.00,Rick Riordan,5,50,Robbie Daymond
8,Merlin Mission Collection,10:56,02-05-17,"1,256.00",Mary Pope Osborne,5,5,Mary Pope Osborne
9,The Tyrant’s Tomb,13:22,24-09-19,820.00,Rick Riordan,5,58,Robbie Daymond
10,"The Titan's Curse: Percy Jackson, Book 3",8:48,14-01-10,820.00,Rick Riordan,4.5,130,Jesse Bernstein
11,Magic Tree House Collection: Books 9-16,5:23,24-08-11,"1,206.00",Mary Pope Osborne,5,6,Mary Pope Osborne
12,Magic Tree House Collection: Books 1-8,6:1,27-09-11,"1,206.00",Mary Pope Osborne,5,7,Mary Pope Osborne
13,Magnus Chase and the Ship of the Dead,12:58,03-10-17,820.00,Rick Riordan,5,41,Michael Crouch
14,Northern Lights,11:55,24-06-21,"1,093.00",Philip Pullman,4,2,Philip Pullman
15,Geronimo Stilton 13 and 14,2:25,08-02-08,467.00,Geronimo Stilton,4.5,33,Bill Lobley
16,Magic Tree House Collection,5:4,26-12-04,"1,206.00",Mary Pope Osborne,5,7,Mary Pope Osborne
17,Exile,14:41,06-11-18,836.00,Shannon Messenger,5,20,Caitlin Kelly
18,Merlin Mission Collection,10:18,02-05-17,"1,256.00",Mary Pope Osborne,5,11,Mary Pope Osborne
19,Neverseen,16:42,06-11-18,"1,003.00",Shannon Messenger,5,13,Caitlin Kelly
20,The Tower of Nero,12:12,06-10-20,615.00,Rick Riordan,5,79,Robbie Daymond
21,"Eldest: The Inheritance Cycle, Book 2",23:29,14-04-09,957.00,Christopher Paolini,4.5,47,Gerrard Doyle
22,Artemis Fowl,6:46,11-04-13,683.00,Eoin Colfer,5,27,Gerry O' Brien
23,Geronimo Stilton 22 & 24,2:37,01-02-11,469.00,Geronimo Stilton,4.5,25,Bill Lobley
24,Percy Jackson and the Battle of the Labyrinth,10:32,21-01-10,820.00,Rick Riordan,5,101,Jesse Bernstein
25,Winnie-the-Pooh,2:46,28-12-03,468.00,A. A. Milne,5,15,Peter Dennis
26,Magic Tree House Collection: Books 25-32,7:9,01-09-20,"1,256.00",Mary Pope Osborne,5,3,Mary Pope Osborne
27,Geronimo Stilton 20 and 21,2:32,01-10-10,469.00,Geronimo Stilton,5,18,Bill Lobley
28,The Red Pyramid,13:44,24-01-13,820.00,Rick Riordan,4.5,37,Jane Collingwood
29,Mystery of the Griefer's Mark,1:53,25-11-14,233.00,Winter Morgan,5,9,Luke Daniels
30,Geronimo Stilton 17,2:28,13-07-09,468.00,Geronimo Stilton,5,8,Bill Lobley
31,The House at Pooh Corner,3:12,05-04-05,374.00,A. A. Milne,5,5,Peter Dennis
32,Mission Unstoppable,6:8,01-08-13,702.00,Dan Gutman,5,8,Michael Goldstrom
33,Darkness of Dragons,10:26,01-08-17,656.00,Tui T. Sutherland,5,8,Shannon Mc Manus
34,"14 Short Stories Bundle for Kids: Adventure, S...",3:13,22-01-19,501.00,Nayomi Phillips,Not rated yet,NaN,Monica Rachelle
35,The Adventures of Rusty,5:41,01-11-18,284.00,Ruskin Bond,4.5,10,Neha Gargava
36,Geronimo Stilton 15 and 16,2:43,08-02-08,467.00,Geronimo Stilton,4,28,Bill Lobley
37,The Lost Heir,7:23,04-02-16,575.00,Tui T. Sutherland,5,9,Shannon Mc Manus
38,Everblaze,14:39,06-11-18,836.00,Shannon Messenger,5,18,Caitlin Kelly
39,Treasure Hunters in Trouble,1:58,31-03-15,668.00,Winter Morgan,5,7,Luke Daniels
40,Lodestar,16:31,06-11-18,"1,003.00",Shannon Messenger,5,19,Caitlin Kelly
41,Curse of the Arctic Star,3:35,28-12-14,305.00,Carolyn Keene,4.5,25,Jorjeana Marie
42,The Ghost of Grey Fox Inn,3:19,20-03-17,305.00,Carolyn Keene,5,11,Jorjeana Marie
43,Rowley Jefferson's Awesome Friendly Adventure,1:31,04-08-20,410.00,Jeff Kinney,4,16,Christopher Gebauer
44,Flashback,23:9,11-12-18,"1,170.00",Shannon Messenger,5,12,Caitlin Kelly
45,Secret of the Red Arrow,3:33,04-11-15,305.00,Franklin W. Dixon,4.5,16,Tim Gregory
46,"The Lightning Thief: Percy Jackson, Book 1",3:51,13-01-10,615.00,Rick Riordan,4,4,Walter Lewis
47,Clash of the Creepers,2:1,07-07-15,233.00,Winter Morgan,5,10,Luke Daniels
48,The Skeletons Strike Back,2:1,07-07-15,233.00,Winter Morgan,5,7,Luke Daniels
49,Dragonslayer,12:44,03-03-20,656.00,Tui T. Sutherland,5,17,Shannon Mc Manus

In [40]:
df=df.rename(columns={'narrator_name1':'narrator_name'})
df

,name,time,releasedate,price,author_name,star,no. ratings,narrator_name
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,5,34,Bill Lobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,4.5,41,Robbie Daymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,4.5,38,Dan Russell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,4.5,12,Soneela Nankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,4.5,181,Jesse Bernstein
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,7:34,09-03-17,596.00,Chris Stewart,Not rated yet,NaN,Chris Stewart
87485,The Alps,10:7,21-02-17,820.00,Stephen O' Shea,Not rated yet,NaN,Robert Fass
87486,The Innocents Abroad,19:4,30-12-16,938.00,Mark Twain,Not rated yet,NaN,Flo Gibson
87487,A Sentimental Journey,4:8,23-02-11,680.00,Laurence Sterne,Not rated yet,NaN,Anton Lesser
87488,Havana,6:1,07-03-17,569.00,Mark Kurlansky,Not rated yet,NaN,Fleet Cooper

In [42]:
df.head(50)

,name,time,releasedate,price,author_name,star,no. ratings,narrator_name
0,Geronimo Stilton 11 & 12,2:20,04-08-08,468.00,Geronimo Stilton,5,34,Bill Lobely
1,The Burning Maze,13:8,01-05-18,820.00,Rick Riordan,4.5,41,Robbie Daymond
2,The Deep End,2:3,06-11-20,410.00,Jeff Kinney,4.5,38,Dan Russell
3,Daughter of the Deep,11:16,05-10-21,615.00,Rick Riordan,4.5,12,Soneela Nankani
4,"The Lightning Thief: Percy Jackson, Book 1",10,13-01-10,820.00,Rick Riordan,4.5,181,Jesse Bernstein
5,The Hunger Games: Special Edition,10:35,30-10-18,656.00,Suzanne Collins,5,72,Tatiana Maslany
6,Quest for the Diamond Sword,2:23,25-11-14,233.00,Winter Morgan,5,11,Luke Daniels
7,The Dark Prophecy,12:32,02-05-17,820.00,Rick Riordan,5,50,Robbie Daymond
8,Merlin Mission Collection,10:56,02-05-17,"1,256.00",Mary Pope Osborne,5,5,Mary Pope Osborne
9,The Tyrant’s Tomb,13:22,24-09-19,820.00,Rick Riordan,5,58,Robbie Daymond
10,"The Titan's Curse: Percy Jackson, Book 3",8:48,14-01-10,820.00,Rick Riordan,4.5,130,Jesse Bernstein
11,Magic Tree House Collection: Books 9-16,5:23,24-08-11,"1,206.00",Mary Pope Osborne,5,6,Mary Pope Osborne
12,Magic Tree House Collection: Books 1-8,6:1,27-09-11,"1,206.00",Mary Pope Osborne,5,7,Mary Pope Osborne
13,Magnus Chase and the Ship of the Dead,12:58,03-10-17,820.00,Rick Riordan,5,41,Michael Crouch
14,Northern Lights,11:55,24-06-21,"1,093.00",Philip Pullman,4,2,Philip Pullman
15,Geronimo Stilton 13 and 14,2:25,08-02-08,467.00,Geronimo Stilton,4.5,33,Bill Lobley
16,Magic Tree House Collection,5:4,26-12-04,"1,206.00",Mary Pope Osborne,5,7,Mary Pope Osborne
17,Exile,14:41,06-11-18,836.00,Shannon Messenger,5,20,Caitlin Kelly
18,Merlin Mission Collection,10:18,02-05-17,"1,256.00",Mary Pope Osborne,5,11,Mary Pope Osborne
19,Neverseen,16:42,06-11-18,"1,003.00",Shannon Messenger,5,13,Caitlin Kelly
20,The Tower of Nero,12:12,06-10-20,615.00,Rick Riordan,5,79,Robbie Daymond
21,"Eldest: The Inheritance Cycle, Book 2",23:29,14-04-09,957.00,Christopher Paolini,4.5,47,Gerrard Doyle
22,Artemis Fowl,6:46,11-04-13,683.00,Eoin Colfer,5,27,Gerry O' Brien
23,Geronimo Stilton 22 & 24,2:37,01-02-11,469.00,Geronimo Stilton,4.5,25,Bill Lobley
24,Percy Jackson and the Battle of the Labyrinth,10:32,21-01-10,820.00,Rick Riordan,5,101,Jesse Bernstein
25,Winnie-the-Pooh,2:46,28-12-03,468.00,A. A. Milne,5,15,Peter Dennis
26,Magic Tree House Collection: Books 25-32,7:9,01-09-20,"1,256.00",Mary Pope Osborne,5,3,Mary Pope Osborne
27,Geronimo Stilton 20 and 21,2:32,01-10-10,469.00,Geronimo Stilton,5,18,Bill Lobley
28,The Red Pyramid,13:44,24-01-13,820.00,Rick Riordan,4.5,37,Jane Collingwood
29,Mystery of the Griefer's Mark,1:53,25-11-14,233.00,Winter Morgan,5,9,Luke Daniels
30,Geronimo Stilton 17,2:28,13-07-09,468.00,Geronimo Stilton,5,8,Bill Lobley
31,The House at Pooh Corner,3:12,05-04-05,374.00,A. A. Milne,5,5,Peter Dennis
32,Mission Unstoppable,6:8,01-08-13,702.00,Dan Gutman,5,8,Michael Goldstrom
33,Darkness of Dragons,10:26,01-08-17,656.00,Tui T. Sutherland,5,8,Shannon Mc Manus
34,"14 Short Stories Bundle for Kids: Adventure, S...",3:13,22-01-19,501.00,Nayomi Phillips,Not rated yet,NaN,Monica Rachelle
35,The Adventures of Rusty,5:41,01-11-18,284.00,Ruskin Bond,4.5,10,Neha Gargava
36,Geronimo Stilton 15 and 16,2:43,08-02-08,467.00,Geronimo Stilton,4,28,Bill Lobley
37,The Lost Heir,7:23,04-02-16,575.00,Tui T. Sutherland,5,9,Shannon Mc Manus
38,Everblaze,14:39,06-11-18,836.00,Shannon Messenger,5,18,Caitlin Kelly
39,Treasure Hunters in Trouble,1:58,31-03-15,668.00,Winter Morgan,5,7,Luke Daniels
40,Lodestar,16:31,06-11-18,"1,003.00",Shannon Messenger,5,19,Caitlin Kelly
41,Curse of the Arctic Star,3:35,28-12-14,305.00,Carolyn Keene,4.5,25,Jorjeana Marie
42,The Ghost of Grey Fox Inn,3:19,20-03-17,305.00,Carolyn Keene,5,11,Jorjeana Marie
43,Rowley Jefferson's Awesome Friendly Adventure,1:31,04-08-20,410.00,Jeff Kinney,4,16,Christopher Gebauer
44,Flashback,23:9,11-12-18,"1,170.00",Shannon Messenger,5,12,Caitlin Kelly
45,Secret of the Red Arrow,3:33,04-11-15,305.00,Franklin W. Dixon,4.5,16,Tim Gregory
46,"The Lightning Thief: Percy Jackson, Book 1",3:51,13-01-10,615.00,Rick Riordan,4,4,Walter Lewis
47,Clash of the Creepers,2:1,07-07-15,233.00,Winter Morgan,5,10,Luke Daniels
48,The Skeletons Strike Back,2:1,07-07-15,233.00,Winter Morgan,5,7,Luke Daniels
49,Dragonslayer,12:44,03-03-20,656.00,Tui T. Sutherland,5,17,Shannon Mc Manus